FROM node:14 AS base

RUN npm install -g npm@7
ENV APP_ROOT /app
RUN mkdir ${APP_ROOT}
WORKDIR ${APP_ROOT}
ADD . ${APP_ROOT}

FROM base AS dependencies

RUN npm install

FROM dependencies AS dev

EXPOSE 8080
CMD [ "npm", "run", "serve" ]